### ISSUE TITLE
i played the 9x9 and found two questions

### ISSUE THREAD

**Issue by l1t1** [inclement/LazyBaduk#2]
it didnt resign at very poor pisition

and at last it hanged

**Comment by l1t1** [comment]
the screen shot
https://userscloud.com/lmdyihn8mq6z

**Comment by inclement** [comment]
Since this is intended mostly as an analysis tool, I've configured Leela Zero to basically never resign. You can end the game yourself when you decide it's over.

The eventual hanging sounds like Leela Zero did want to resign, but the app doesn't handle that well. I'll look into it, thanks for the report.
